GIT = 'git'
CONFILE_FILE_NAME = 'config.yaml'
TEMPLATES_DIR = 'templates'

# Constants for YAML configuration
USE_TEMPLATE = 'use_template'
GIT_REPOSITORY = 'git_repository'
PROJECT_VARS = 'project_vars'
ARTIFACTS = 'artifacts'
GENERATE_ARTIFACTS = 'generate_artifacts'
DISABLE_ARTIFACTS = 'disable_artifacts'
CONTINUE_ON_FAILURE = 'continue_on_failure'
DISPLAY_PIPELINE_OUTPUT = 'display_pipeline_output'
COMMAND = 'command'
NAME = 'name'
ENABLED = 'enabled'
PATHS = 'paths'
ARCHIVE = 'archive'
ASSEMBLE = 'assemble'
STAGES = 'stages'
